// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Db;

namespace MyWebApi.Migrations
{
    [DbContext(typeof(MyWebApiContext))]
    [Migration("20190714080616_CreateIndex_Name")]
    partial class CreateIndex_Name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebApi.Models.Good", b =>
                {
                    b.Property<Guid>("GoodId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("GoodId");

                    b.HasIndex("Name")
                        .HasAnnotation("SqlServer:Include", new[] { "Description", "Price" });

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            GoodId = new Guid("33a644db-6d21-4126-a985-112637d1ef2a"),
                            Description = "New soccer ball",
                            Name = "Soccer ball",
                            Price = 111.0m
                        },
                        new
                        {
                            GoodId = new Guid("eb9303fc-7a7f-4a50-bb1e-2df5aef221de"),
                            Description = "New foot ball",
                            Name = "Foot ball",
                            Price = 221.0m
                        });
                });

            modelBuilder.Entity("MyWebApi.Models.Pet", b =>
                {
                    b.Property<Guid>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("PetId");

                    b.HasIndex("Name")
                        .HasAnnotation("SqlServer:Include", new[] { "Description", "Price" });

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = new Guid("077ded3b-8f61-4f02-bd7c-e75220ecff05"),
                            Description = "Cute cat",
                            Name = "Cat",
                            Price = 111.0m
                        },
                        new
                        {
                            PetId = new Guid("0a5bc2ae-a65b-4bf6-ae75-238d43eeb55e"),
                            Description = "Good boy",
                            Name = "Dog",
                            Price = 111.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
