// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Db;

namespace MyWebApi.Migrations
{
    [DbContext(typeof(MyWebApiContext))]
    [Migration("20190718131426_CreateIndex_Name")]
    partial class CreateIndex_Name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebApi.Models.Good", b =>
                {
                    b.Property<Guid>("GoodId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("GoodId");

                    b.HasIndex("Name")
                        .HasAnnotation("SqlServer:Include", new[] { "Description", "Price" });

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            GoodId = new Guid("90f3bf1e-18a9-4601-b03d-d83a9f99ca4d"),
                            Description = "New soccer ball",
                            Name = "Soccer ball",
                            Price = 111.0m
                        },
                        new
                        {
                            GoodId = new Guid("eb0738cd-a0cb-428c-8e3a-85c99d880b80"),
                            Description = "New foot ball",
                            Name = "Foot ball",
                            Price = 221.0m
                        });
                });

            modelBuilder.Entity("MyWebApi.Models.Pet", b =>
                {
                    b.Property<Guid>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PetId");

                    b.HasIndex("Name")
                        .HasAnnotation("SqlServer:Include", new[] { "Description", "Price" });

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = new Guid("785a153a-f0d9-4d66-b75e-61cf22443be4"),
                            Description = "Cute cat",
                            Name = "Cat",
                            Price = 111.0m
                        },
                        new
                        {
                            PetId = new Guid("b61fac69-cc44-4a3c-94da-b2205062b1db"),
                            Description = "Good boy",
                            Name = "Dog",
                            Price = 111.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
